title: Woodlands Secondary School
url: https://www.woodlandssec.moe.edu.sg
favicon: /images/schoolcrest.png
colors:
  primary-color: "#11439c"
  secondary-color: "#0054b4"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#11439c"
    - title: media-color-three
      color: "#11439c"
    - title: media-color-four
      color: "#11439c"
    - title: media-color-five
      color: "#11439c"
description: Every Woodlander a gift to society
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1qrsrqf24putd.amplifyapp.com
prod: https://master.d1qrsrqf24putd.amplifyapp.com
shareicon: /images/schoolcrest.png
is_government: false
facebook-pixel: ""
google_analytics: G-MXGJQN4G1Z
linkedin-insights: ""
resources_name: updates
